version: '3.8'

services:
  erpdb:
    image: 1devops2/erpnext14-with-github-actions:db
    container_name: erpdb
    environment:
      MARIADB_ROOT_PASSWORD: whitecoke
    volumes:
      - ./conf:/etc/mysql/conf.d
    restart: unless-stopped 

  erp:
    image: 1devops2/erpnext14-with-github-actions:app
    container_name: erp
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
      - "3306:3306"
    volumes:
      - ./startup-script:/docker-entrypoint-initdb.d 
    depends_on:
       - erpdb