name: deploy erp app

on:
  push:
    branches: [ "erpnext-with-github-actions" ]

jobs:
  deploy-erp:
    runs-on: ubuntu-latest

    steps:
    # - name: install ssh keys
    #   run: |
    #     install -m 600 -D /dev/null ~/.ssh/id_rsa
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    # - name: Create SSH config file
    #   run: |
    #         echo "Host *" > ~/.ssh/config
    #         echo "    ServerAliveInterval 20" >> ~/.ssh/config
    #         echo "    TCPKeepAlive no" >> ~/.ssh/config
            
    - name: SSH and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        # port: 22
        script: |
            ls -la
            pwd

        # run: |
        #     echo 'Hello from remote server' && \
        #     apt-get update && \
        #     apt-get install -y git docker.io docker-compose && \
        #     git clone -b erpnext-with-github-actions https://github.com/1DevOps2/ERPNext.git && cd ERPNext && \
        #     docker-compose -f docker-compose.yml up --build -d && \
        #     exit"

    - name: cleanup
      run: rm -rf ~/.ssh
