name: deploy Erp app

on:
  push:
    branches: [ "erpnext-with-github-actions" ]

jobs:
  deploy-erp:
    runs-on: ubuntu-latest

    steps:
            
    - name: Deploy to the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        # port: 22
        script: |
            # installing docker
            # sudo apt-get install docker.io -y

            # installing /git
            # sudo apt-get install git -y

            # clone the project
            git clone -b erpnext-with-github-actions https://github.com/1DevOps2/ERPNext.git 

            # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition.
            # sudo sysctl vm.overcommit_memory=1

            # navigate to cloned repo
            cd ERPNext 

            # CREATE NETWORK
            docker network create erpnet

            # RUN MARIADB CONTAINER.
            docker run -it  --net erpnet --name erpdb -e MYSQL_ROOT_PASSWORD=1QWERT2 -v $(pwd)/conf:/etc/mysql/conf.d -d 1devops2/erpnextdb:14

            # RUN FRAPPE-APP CONTAINER
            docker run -it --network erpnet --name erp -p 8000:8000 -p 9000:9000 -p3306:3306 -d 1devops2/erpnext:14

            docker exec erp bash -c " 
            cd frappe-bench && \
            bench new-site erp.net --admin-password '321' --mariadb-root-username root --mariadb-root-password 1QWERT2 --db-host erpdb && \
            bench --site erp.net install-app erpnext && \
            bench get-app branch version-14 https://github.com/yrestom/POS-Awesome.git && \
            bench setup requirements && \
            bench build --app posawesome && \
            bench --site erp.net install-app posawesome && \
            cd /home/frappe/frappe-bench/sites && echo 'erp.net' >currentsite.txt && \
            cd /home/frappe/frappe-bench &&  bench start 
            exit
            "

            # exit the machine
            exit


    - name: cleanup
      run: rm -rf ~/.ssh
